### ISSUE TITLE
ID SUPERA EL 40% DE MORTALIDAD.

### ISSUE THREAD

**Issue by davidagm74** [davidagm74/Validacion-1-4-2020#1]

**Comment by gabrielhb4555** [comment]
USUARIO BA07, Id del registro: 1000001743, BENEFICIARIOS ROSALINNA BATISTA CARRASCO,
CEDULA 08000021751.
LA MORTALIDAD ESTA EN UN 100% Y NO TIENE EL PUNTO GPS
