### ISSUE TITLE
PENDIENTES DE FOTOS CEDULA, FICHA Y/O PANORAMICA.

### ISSUE THREAD

**Issue by davidagm74** [davidagm74/Validacion-1-4-2020#4]

**Comment by gabrielhb4555** [comment]
USUARIO BA06, Id del registro: 1000001515, BENEFICIARIOS LUIS MANUEL FERRERAS TRINIDAD, CEDULA 01800087106.
PENDIENTE  DE FOTO DE CEDULA.
